# Generated by Django 5.0.7 on 2025-10-28 05:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("p1_id", models.CharField(blank=True, max_length=64, null=True)),
                ("p2_id", models.CharField(blank=True, max_length=64, null=True)),
                ("p1_hp", models.IntegerField(default=40)),
                ("p2_hp", models.IntegerField(default=40)),
                ("p1_tokens", models.IntegerField(default=0)),
                ("p2_tokens", models.IntegerField(default=0)),
                ("turn", models.IntegerField(default=1)),
                ("deadline", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished", models.BooleanField(default=False)),
                ("winner", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Turn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("deadline", models.DateTimeField()),
                ("resolved", models.BooleanField(default=False)),
                (
                    "p1_action",
                    models.CharField(
                        choices=[
                            ("attack", "Attack"),
                            ("guard", "Guard"),
                            ("charge", "Charge"),
                            ("charged_attack", "Charged Attack"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "p2_action",
                    models.CharField(
                        choices=[
                            ("attack", "Attack"),
                            ("guard", "Guard"),
                            ("charge", "Charge"),
                            ("charged_attack", "Charged Attack"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="arena.room",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("room", "number")},
            },
        ),
    ]
